"""add email delivery columns

Revision ID: 2c058298fe33
Revises: d9cbf3790ae9
Create Date: 2026-07-12 16:35:56.323323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c058298fe33'
down_revision: Union[str, Sequence[str], None] = 'd9cbf3790ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('sent_to_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'sent_to_email')
    op.drop_column('invoices', 'sent_at')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
