"""add stripe checkout session id and paid_at to invoices, create stripe_events

Revision ID: 5c026e80f6a8
Revises: 1a9b5cceff04
Create Date: 2026-07-11 00:46:24.501153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c026e80f6a8'
down_revision: Union[str, Sequence[str], None] = '1a9b5cceff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('stripe_checkout_session_id', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'stripe_checkout_session_id')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
