"""add pdf_object_key to invoices

Revision ID: d9cbf3790ae9
Revises: 5c026e80f6a8
Create Date: 2026-07-11 18:47:54.104458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cbf3790ae9'
down_revision: Union[str, Sequence[str], None] = '5c026e80f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('pdf_object_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'pdf_object_key')
    # ### end Alembic commands ###
